#### MinerTrack Anti-Xray Configuration - config.yml ##############################
#
#   Welcome to MinerTrack anti-xray configuration file.
#   This file defines global settings specifically optimized for anti-xray detection.
#
#   If you have any issues, please join our Discord group for support:
#   https://discord.gg/H3PM8U3y
#
##################################################################################

# Check for updates on startup (recommended for latest optimizations).
check_update: true

# Permission Cache refresh interval (seconds, default: 15)
permission_refresh_interval: 15

# Visual effect when a player is kicked using /minertrack kick (default: true)
kick_strike_lightning: true

# Log Violations (default: true)
# Logs all detections in /plugins/MinerTrack/logs for easier monitoring.
log_file: true

# Auto-delete outdated logs after specified days (-1 to disable auto-deletion)
delete_time: 30

# Deny Bypass Permission - force checks on all players, including Operators.
disable_bypass_permission: false

xray:
  enable: true  # Enable X-ray detection

  # At what height should I start detecting X-Ray?
  # Worlds that are not listed do not have XRay detection.
  worlds:
    world:
      enable: true
      max-height: 64
    world_nether:
      enable: true
      max-height: 128
    world_the_end:
      enable: false
    all_unnamed_world:
      enable: false

  
  # The type of ore a player has to mine before being able to be checked
  # List of allowed materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  rare-ores:
    - ANCIENT_DEBRIS
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE

  # Traceback duration to analyze potential x-ray behaviors (Unit: minute)
  # Turning it down will sacrifice detection power to reduce memory footprint, and vice versa.
  trace_back_length: 10
  
  # Mined length record limit (Unit: block)
  max_path_length: 500
  
  # Path record is reset after the player VL is 0 {n} minutes.
  trace_remove: 5
  
  caveBypassAirCount: 4
  
  # Violation threshold
  ViolationThreshold:
    turnCountThreshold: 10
    veinCountThreshold: 3

  # Violation level decay settings (Unit: minute)
  decay:
    interval: 2
    amount: 1

  # Commands executed at specified violation thresholds
  commands:
    4: 'minertrack notify &f%player% &7triggered &fX-Ray &7detection [&cVL: 4&7]'
    6: 'minertrack notify &f%player% &7triggered &fX-Ray &7detection [&cVL: 6&7]'
    8: 'minertrack kick %player% X-Ray'
